# Generated by Django 5.2.3 on 2025-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('wheels', models.CharField(choices=[('TWO', 'two'), ('FOUR', 'four'), ('SIX', 'six'), ('OTHER', 'other')], max_length=10)),
                ('brand', models.CharField(choices=[('FORD', 'ford'), ('CHEVROLET', 'chevrolet'), ('FIAT', 'fiat'), ('TOYOTA', 'toyota'), ('HONDA', 'honda'), ('OTHER', 'other')], max_length=20)),
                ('model', models.CharField(choices=[('SEDAN', 'sedan'), ('HATCH', 'hatchback'), ('SUV', 'suv'), ('PICKUP', 'pickup'), ('OTHER', 'other')], max_length=20)),
                ('manufacture_date', models.DateField()),
                ('weight_kg', models.FloatField()),
                ('fuel', models.CharField(choices=[('GASOLINE', 'gasoline'), ('DIESEL', 'diesel'), ('ELECTRIC', 'electric'), ('HYBRID', 'hybrid'), ('ETHANOL', 'ethanol')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('MANUAL', 'manual'), ('AUTOMATIC', 'automatic'), ('CVT', 'cvt'), ('SEMI_AUTOMATIC', 'semi')], max_length=20)),
                ('ipva', models.CharField(choices=[('PAID', 'paid'), ('LATE', 'late'), ('EXEMPT', 'exempt')], max_length=10)),
                ('sunroof', models.BooleanField(default=False)),
                ('nitro', models.BooleanField(default=False)),
            ],
        ),
    ]
